.PHONY: clean All

All:
	@echo "==========Building project:[ Challenge_MySolution - Debug ]=========="
	@cd "Challenge_MySolution" && "$(MAKE)" -f  "Challenge_MySolution.mk"
clean:
	@echo "==========Cleaning project:[ Challenge_MySolution - Debug ]----------"
	@cd "Challenge_MySolution" && "$(MAKE)" -f  "Challenge_MySolution.mk" clean
