.PHONY: clean All

All:
	@echo "==========Building project:[ Test - Debug ]=========="
	@cd "test" && "$(MAKE)" -f  "Test.mk"
clean:
	@echo "==========Cleaning project:[ Test - Debug ]----------"
	@cd "test" && "$(MAKE)" -f  "Test.mk" clean
